org: surajyadav7977
service: aws-api-http

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  hello:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: get        
  
  bye:
    handler: bye.handler
    events:
      - httpApi:
          path: /bye
          method: get
